In [2]:
import pandas as pd

datos={'nombre':['Mariana','Ana','Elsa','Gustavo',
                 'Pedro','Raul','Carlos','Jose','Luis'],
       'saldo':[10000.00,8000.00,9000.00,2000.00,
                2100.00,12000.00,5000.00,10000.00,200.00],
       'pais':['Argentina','Bolivia','Chile','Colombia',
               'Costa Rica','Ecuador','Mexico','Peru','Peru']}
datos=pd.DataFrame(datos)
datos

nombre    saldo        pais
0  Mariana  10000.0   Argentina
1      Ana   8000.0     Bolivia
2     Elsa   9000.0       Chile
3  Gustavo   2000.0    Colombia
4    Pedro   2100.0  Costa Rica
5     Raul  12000.0     Ecuador
6   Carlos   5000.0      Mexico
7     Jose  10000.0        Peru
8     Luis    200.0        Peru

In [3]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   nombre  9 non-null      object 
 1   saldo   9 non-null      float64
 2   pais    9 non-null      object 
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes


In [7]:
datos['pais']=datos['pais'].astype('category')
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   nombre  9 non-null      object  
 1   saldo   9 non-null      float64 
 2   pais    9 non-null      category
dtypes: category(1), float64(1), object(1)
memory usage: 649.0+ bytes


In [58]:
datos['pais']

0     Argentina
1       Bolivia
2         Chile
3      Colombia
4    Costa Rica
5       Ecuador
6        Mexico
7          Peru
8          Peru
Name: pais, dtype: category
Categories (8, object): ['Argentina', 'Bolivia', 'Chile', 'Colombia', 'Costa Rica', 'Ecuador', 'Mexico', 'Peru']

<h2>Codificacion de Categoria One-hot</h2>

<h3>Los datos Nominales : No tienen orden logico o jerarquico</h3>
<p>Ejemplos: Colores, Genero, Ciudad.</p>
<b>El modelo no debe asumir ningun tipo de orden en estas categorias.</b>

In [59]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)
#Ajustar y transformar
encoded_array=encoder.fit_transform(datos[['pais']])

In [60]:
print(type(encoded_array))
print(encoded_array)

<class 'numpy.ndarray'>
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [63]:
encoded_datos=pd.DataFrame(
    encoded_array,columns=encoder.get_feature_names_out(['pais'])
)

In [67]:
datos_final=pd.concat([datos.drop('pais',axis=1),encoded_datos],axis=1)

In [68]:
datos_final

nombre    saldo  pais_Argentina  pais_Bolivia  pais_Chile  pais_Colombia  \
0  Mariana  10000.0             1.0           0.0         0.0            0.0   
1      Ana   8000.0             0.0           1.0         0.0            0.0   
2     Elsa   9000.0             0.0           0.0         1.0            0.0   
3  Gustavo   2000.0             0.0           0.0         0.0            1.0   
4    Pedro   2100.0             0.0           0.0         0.0            0.0   
5     Raul  12000.0             0.0           0.0         0.0            0.0   
6   Carlos   5000.0             0.0           0.0         0.0            0.0   
7     Jose  10000.0             0.0           0.0         0.0            0.0   
8     Luis    200.0             0.0           0.0         0.0            0.0   

   pais_Costa Rica  pais_Ecuador  pais_Mexico  pais_Peru  
0              0.0           0.0          0.0        0.0  
1              0.0           0.0          0.0        0.0  
2              0.0           0.0          0.0        0.0  
3              0.0           0.0          0.0        0.0  
4              1.0           0.0          0.0        0.0  
5              0.0           1.0          0.0        0.0  
6              0.0           0.0          1.0        0.0  
7              0.0           0.0          0.0        1.0  
8              0.0           0.0          0.0        1.0